### ISSUE TITLE
API/endepunkter for å serve JSON på forespørsel

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-resource-service#21]

**Comment by NilsOveTen** [comment]
> @NilsOveTen Dette er et veldig vagt issue, men det er kanskje Done allerede? Er del av større epic.

Løst? Nei. Er dette et unødvendig issue? Ja.

**Comment by terjesyl** [comment]
Kan du opprette nødvendige issues og legge dem til i listen i epicet https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/692?

**Comment by NilsOveTen** [comment]
> Kan du opprette nødvendige issues og legge dem til i listen i epicet [Informasjonsforvaltning/fdk-issue-tracker#692](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/692)?

Issues har jeg oppretta for lenge siden. Men ok, kan liste de opp i epic'en
