### ISSUE TITLE
Støtte GraphQL

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-resource-service#22]
## TODO
Ønskelig, må avklares og prioriteres.
(finn ut av hva som må gjøres og settes opp)

**Comment by NilsOveTen** [comment]
> @NilsOveTen ønskelig og realistisk å få til på kort tid? Ellers foreslår jeg at vi lukker saken og tar det opp senere om det blir aktuelt.

Hvorfor er det ønskelig? Jeg kan ikke se for meg at det er verdt tida vi ville brukt på det...

**Comment by terjesyl** [comment]
Kom innspill fra Jeff på det. Kan redusere trafikkmengden fra portal til backend når kan vi gjøre mer målrettede spørringer.

**Comment by NilsOveTen** [comment]
> Kom innspill fra Jeff på det. Kan redusere trafikkmengden fra portal til backend når kan vi gjøre mer målrettede spørringer.

Ok, hvis det en gang i fremtiden kommer et reelt behov for det fra portal så kan vi se an å legge det til.
