### ISSUE TITLE
Mulighet for å filtrere liste-endepunktene basert på liste med fdkId

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-resource-service#37]

**Comment by KjerstiSteien** [comment]
@NilsOveTen kan du beskrive hvilken sak som blokkerer denne?

**Comment by NilsOveTen** [comment]
> @NilsOveTen kan du beskrive hvilken sak som blokkerer denne?

Blokkeres er vel egentlig å ta litt hardt i, men har lite lyst å gjøre den før denne er ferdig: https://github.com/Informasjonsforvaltning/fdk-resource-service/issues/37

Det blir unødvendig rotete om denne tas først

**Comment by NilsOveTen** [comment]
Startet på å implementere denne som query-param i går, men @jeffreiffers kommenterte at vi fort kan støte på lengdeproblem, siden idene vi bruker er relativt lange

Så Vi går over til at henting av liste er POST, med eventuelle filter i body, men vil da fjerne støtten for removed-filteret før jeg starter en større refaktorering av endepunktene
